# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('exservice', models.CharField(max_length=10)),
            ],
        ),
    ]
